import Head from "next/head";
import Navbar from "../components/Navbar";

export default function About() {
    return ( 
        <div className="min-h-screen flex flex-col justify-center items-center">
        <Head>
          <title>Sidetrade Next Template</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
            rel="stylesheet"

          />
        </Head>
        <main className="py-20 flex flex-col flex-1 justify-center items-center">
        <h1 className="m-10 leading-snug text-6xl text-center">

          <a
            className="text-blue-600 no-underline hover:underline focus:underline"
            href="https://nextjs.org"
          >

          </a>
        </h1>

        <p className="leading-normal text-6xl text-center font-italic 
        ">
         About us 

        </p>
        </main>
        </div>

    )
}

